[MOSIP-29967] pre-release-check
Signed-off-by: Rakshitha650 <rakshitham38@gmail.com>

diff --git a/.github/workflows/dev-pre-check.yml b/.github/workflows/dev-pre-check.yml
--- a/.github/workflows/dev-pre-check.yml
+++ b/.github/workflows/dev-pre-check.yml
@@ -35,9 +35,10 @@ jobs:
         run: |
           # Your script or command to check dynamically provided artifact version
           version_to_check="${{ inputs.VERSION }}"
-          if ! grep -r -E "<artifactId>[^<]+</artifactId>|<version>${version_to_check}</version>" --include="pom.xml" .; then
-            echo "Error: Dynamically provided artifact version not found."
+          if ! grep -r -E "<artifactId>[^<]+</artifactId>|<version>${version_to_check}</version>" --include="pom.xml" . | grep "<version>${version_to_check}</version>"; then
+            echo "Error: Dynamically provided artifact version '${version_to_check}' not found."
             exit 1
           fi
+
 
 # Example command: python check_version.py 2.0.1
