[MOSIP-29967] pre-release-check
Signed-off-by: Rakshitha650 <rakshitham38@gmail.com>

diff --git a/.github/workflows/dev-pre-check.yml b/.github/workflows/dev-pre-check.yml
--- a/.github/workflows/dev-pre-check.yml
+++ b/.github/workflows/dev-pre-check.yml
@@ -1,4 +1,4 @@
-name: List Artifacts and Dependencies
+name: Check Artifact Version
 
 on:
   workflow_dispatch:
@@ -12,7 +12,7 @@ on:
         required: true
 
 jobs:
-  list-artifacts:
+  check-artifact-version:
     runs-on: ubuntu-latest
 
     steps:
@@ -25,18 +25,19 @@ jobs:
           distribution: 'adopt'
           java-version: '11'
 
-      - name: List Artifacts and Dependencies
+      - name: Check Artifact Version
         run: |
-          # Search for all POM files in the repository
-          pom_files=$(find . -name 'pom.xml')
-
           # Extract the dynamically provided artifact version from the user input
           VERSION=${{ github.event.inputs.VERSION }}
           
-          # Search for the artifact version in POM files
+          # Search for the artifact version in POM files as artifact or dependency version
           echo "Searching for artifact version: $VERSION"
-          for file in $pom_files; do
-            if grep -qE "<version>$VERSION</version>|<version>${VERSION}-SNAPSHOT</version>" $file; then
-              echo "Artifact version $VERSION found in $file."
-            fi
-          done || true
+          files=$(find . -type f -name '*.xml' ! -name 'pom.xml' -print0 | xargs -0 grep -l -E "<version>$VERSION</version>|<dependency>\s*<version>$VERSION</version>|<version>$VERSION-SNAPSHOT</version>|<dependency>\s*<version>$VERSION-SNAPSHOT</version>" | sort -u)
+
+          if [ -z "$files" ]; then
+            echo "Artifact version $VERSION not found in any POM files."
+            exit 1
+          else
+            echo "Artifact version $VERSION found in the following files:"
+            echo "$files"
+          fi
